import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { articles } from "../content/articles.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "dist");
const repo = "faa-part-107-web";
const origin = `https://mcyj.github.io/${repo}`;
const base = `/${repo}`;
const checkedAt = "2026-09-18";
const faaPilot = "https://www.faa.gov/uas/commercial_operators/become_a_drone_pilot";
const faaAcs = "https://www.faa.gov/training_testing/testing/acs/uas_acs.pdf";
const faaTesting = "https://www.faa.gov/training_testing/testing";
const faaSupplements = "https://www.faa.gov/training_testing/testing/supplements";
const playUrl = "https://play.google.com/store/apps/details?id=app.mcyj.examprep.glb0002";
const appStoreUrl = "https://apps.apple.com/us/app/faa-part-107/id6795569826";
const supportEmail = "june1012june@gmail.com";

const esc = (value) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
async function put(path, contents) { const target = join(out, path); await mkdir(dirname(target), { recursive: true }); await writeFile(target, contents); }

function nav() {
  return `<header class="site-header"><a class="brand" href="${base}/en/"><img src="${base}/assets/app-icon.svg" width="44" height="44" alt=""><span>FAA Part 107<br><strong>Exam Prep</strong></span></a><nav aria-label="Primary"><a href="${base}/en/guides/">Flight guides</a><a href="${base}/en/faq/">FAQ</a><a href="${base}/en/support/">Support</a></nav></header>`;
}
function footer() {
  return `<footer><div><strong>FAA Part 107 Exam Prep</strong><p>Independent study support from RushLabs. Not affiliated with or endorsed by the FAA.</p></div><nav aria-label="Legal"><a href="${base}/en/privacy/">Privacy</a><a href="${base}/en/terms/">Terms</a><a href="${base}/en/support/">Support</a><a href="${base}/en/contact/">Contact</a></nav><p class="source-note">Official details checked ${checkedAt}. Current FAA rules and testing-provider instructions control.</p><p class="trademark">Apple, the Apple logo, and App Store are trademarks of Apple Inc., registered in the U.S. and other countries.</p></footer>`;
}
function layout({ title, description, path, body, type = "website", jsonLd = null }) {
  const canonical = `${origin}${path}`;
  const schema = jsonLd ? `<script type="application/ld+json">${JSON.stringify(jsonLd).replaceAll("<", "\\u003c")}</script>` : "";
  return `<!doctype html><html lang="en-US"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="en-US" href="${canonical}"><link rel="alternate" hreflang="x-default" href="${canonical}"><meta property="og:type" content="${type}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:site_name" content="FAA Part 107 Exam Prep"><meta name="twitter:card" content="summary"><meta name="theme-color" content="#071827"><link rel="icon" href="${base}/assets/app-icon.svg"><link rel="stylesheet" href="${base}/assets/styles.css">${schema}</head><body><a class="skip" href="#main">Skip to content</a><div class="page-shell">${nav()}<main id="main">${body}</main>${footer()}</div></body></html>`;
}
function storeButtons(label = "Get the app") {
  return `<div class="store-block" aria-labelledby="store-heading"><p class="eyebrow" id="store-heading">${label}</p><div class="store-row"><a href="${appStoreUrl}" aria-label="Download FAA Part 107 on the App Store"><img src="${base}/assets/app-store-badge.svg" width="180" height="60" alt="Download on the App Store"></a><a href="${playUrl}" aria-label="Get FAA Part 107 Drone Exam Prep on Google Play"><img src="${base}/assets/google-play-badge.png" width="194" height="75" alt="Get it on Google Play"></a></div><p class="store-note">Available now on the App Store and Google Play.</p></div>`;
}

const homeBody = `<section class="hero"><div class="radar" aria-hidden="true"><span></span><i></i></div><div class="hero-copy"><p class="eyebrow">Remote Pilot · Small UAS</p><h1>Know the airspace.<br><span>Own the decision.</span></h1><p class="lede">Focused FAA Part 107 practice for regulations, charts, weather, aircraft performance and safe operations.</p>${storeButtons()}</div><div class="phone-stage"><img src="${base}/assets/screenshots/question.png" width="393" height="852" alt="FAA Part 107 practice question screen"></div></section>
<section class="proof-strip" aria-label="App and certification highlights"><div><strong>500</strong><span>independently authored practice questions</span></div><div><strong>UAG</strong><span>initial aeronautical knowledge test</span></div><div><strong>24 months</strong><span>recurrent-training currency window</span></div></section>
<section class="split section"><div><p class="eyebrow">Certification route</p><h2>From an FAA Tracking Number to a safe first mission.</h2><p>First-time applicants create an IACRA profile, schedule the UAG knowledge test, pass, then apply for the Remote Pilot Certificate. The certificate itself is permanent unless revoked, but operating currency requires recurrent training.</p><a class="text-link" href="${base}/en/guides/certificate-path/">See the certificate path <span aria-hidden="true">→</span></a></div><div class="route-card"><div><span>01</span><strong>Get an FTN</strong><p>Create your IACRA profile before scheduling.</p></div><div><span>02</span><strong>Pass UAG</strong><p>Prepare from the current Remote Pilot ACS.</p></div><div><span>03</span><strong>Apply & stay current</strong><p>Complete IACRA and recurrent training on time.</p></div><p class="source-note">Source: FAA, checked ${checkedAt}.</p></div></section>
<section class="section"><div class="section-heading"><div><p class="eyebrow">Inside the app</p><h2>Question. Reason. Fly the scenario.</h2></div><p>Work through focused practice, study explanations, save difficult items and move into mixed practice tests.</p></div><div class="screens"><figure><img loading="lazy" src="${base}/assets/screenshots/question.png" width="393" height="852" alt="A Part 107 practice question"><figcaption>Commit to a decision.</figcaption></figure><figure><img loading="lazy" src="${base}/assets/screenshots/explanation.png" width="393" height="852" alt="A Part 107 answer explanation"><figcaption>Understand the operational reason.</figcaption></figure><figure><img loading="lazy" src="${base}/assets/screenshots/practice-tests.png" width="393" height="852" alt="Part 107 practice test list"><figcaption>Test the full mission mix.</figcaption></figure></div></section>
<section class="section guide-preview"><div class="section-heading"><div><p class="eyebrow">Free flight guides</p><h2>Study the rule in context.</h2></div><a class="text-link" href="${base}/en/guides/">Browse all ${articles.length} guides <span aria-hidden="true">→</span></a></div><div class="guide-grid">${articles.slice(0, 6).map((a, i) => `<a class="guide-card" href="${base}/en/guides/${a.slug}/"><span>${String(i + 1).padStart(2, "0")} · ${a.category}</span><h3>${a.title}</h3><p>${a.description}</p></a>`).join("")}</div></section>
<section class="final-cta"><p class="eyebrow">Ready for the next sortie?</p><h2>Build decisions you can defend.</h2><p>Practice with FAA Part 107 Exam Prep on iPhone, iPad and Android.</p>${storeButtons("App availability")}</section>`;

const softwareSchema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "FAA Part 107", applicationCategory: "EducationalApplication", operatingSystem: "Android, iOS", description: "Independent FAA Part 107 practice and mock-exam app.", url: `${origin}/en/`, downloadUrl: [playUrl, appStoreUrl], publisher: { "@type": "Organization", name: "RushLabs" }, offers: { "@type": "Offer", price: "0", priceCurrency: "USD", availability: "https://schema.org/InStock" } };
const guidesBody = `<section class="page-intro"><p class="eyebrow">Flight library</p><h1>Part 107 study guides</h1><p>Original preparation guidance grounded in current FAA materials. Regulations and provider instructions can change; verify dated facts before acting.</p></section><section class="guide-grid all-guides">${articles.map((a) => `<a class="guide-card" href="${base}/en/guides/${a.slug}/"><span>${a.category}</span><h2>${a.title}</h2><p>${a.description}</p></a>`).join("")}</section><aside class="official-source"><h2>Fly from official information</h2><p>Use these guides for study structure. Use current FAA sources for certification and operational decisions.</p><div><a href="${faaPilot}">FAA certification pathway</a><a href="${faaAcs}">Remote Pilot ACS</a><a href="${faaTesting}">FAA Airman Testing</a></div></aside>`;

function articlePage(article) {
  const related = article.related.map((slug) => articles.find((item) => item.slug === slug)).filter(Boolean);
  const body = `<article class="article"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="${base}/en/">Home</a><span>/</span><a href="${base}/en/guides/">Guides</a><span>/</span><span aria-current="page">${article.category}</span></nav><header><p class="eyebrow">${article.category}</p><h1>${article.title}</h1><p class="lede">${article.description}</p><p class="article-meta">Reviewed against FAA sources · ${checkedAt}</p></header><div class="article-layout"><div class="article-copy">${article.body}<section class="sources"><h2>Official sources</h2><ul><li><a href="${faaPilot}">FAA: Become a Certificated Remote Pilot</a></li><li><a href="${faaAcs}">FAA Remote Pilot sUAS ACS</a></li><li><a href="${faaTesting}">FAA Airman Testing</a></li><li><a href="${faaSupplements}">FAA testing supplements</a></li></ul><p>Current regulations, FAA guidance, authorizations and testing-provider instructions control over this summary.</p></section></div><aside class="article-aside"><img src="${base}/assets/app-icon.svg" width="88" height="88" alt="FAA Part 107 app icon"><h2>Practise the mission</h2><p>Use original questions, explanations, saved items and practice tests in the app.</p><a class="status-pill live" href="${playUrl}">Google Play</a><a class="status-pill live" href="${appStoreUrl}">App Store</a></aside></div><section class="related"><p class="eyebrow">Continue the briefing</p><div class="guide-grid">${related.map((item) => `<a class="guide-card" href="${base}/en/guides/${item.slug}/"><span>${item.category}</span><h3>${item.title}</h3></a>`).join("")}</div></section></article>`;
  const schema = { "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.description, datePublished: checkedAt, dateModified: checkedAt, inLanguage: "en-US", author: { "@type": "Organization", name: "RushLabs" }, publisher: { "@type": "Organization", name: "RushLabs" }, mainEntityOfPage: `${origin}/en/guides/${article.slug}/` };
  return layout({ title: `${article.title} | FAA Part 107 Exam Prep`, description: article.description, path: `/en/guides/${article.slug}/`, type: "article", body, jsonLd: schema });
}

const faqItems = [
  ["Is this an official FAA app?", "No. It is independently produced by RushLabs and is not affiliated with or endorsed by the FAA."],
  ["Which test does a first-time pilot take?", "The FAA identifies the initial aeronautical knowledge test as Unmanned Aircraft General – Small, or UAG."],
  ["Does the Remote Pilot Certificate expire?", "The FAA says the certificate is permanent unless revoked. To operate under Part 107, you must maintain aeronautical-knowledge recency through the appropriate online training within the previous 24 calendar months."],
  ["What does the app include?", "The current listings describe 500 independently authored questions, explanations, practice tests, progress, saved items and an optional Lock Quiz."],
  ["Does the app reproduce live FAA exam questions?", "No. It contains independently authored study material and does not claim access to secured examination questions."],
  ["Do I need a RushLabs account?", "No. The current app is local-first and does not require a RushLabs account."],
  ["Where can I download it?", "The exact FAA Part 107 product is publicly available on both Google Play and the App Store through the badges on this website."],
  ["Where should I verify current rules?", "Use FAA regulations and current FAA guidance for operations, the FAA certification page for the process, and the FAA-linked testing provider for appointment requirements and fees."],
];
const faqBody = `<section class="page-intro"><p class="eyebrow">Questions & answers</p><h1>Clear boundaries before takeoff.</h1><p>Certification, currency, app scope and official-source answers.</p></section><section class="faq-list">${faqItems.map(([q, a]) => `<details><summary>${q}</summary><p>${a}</p></details>`).join("")}</section>`;
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqItems.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };

const privacyBody = `<article class="policy"><p class="eyebrow">Legal</p><h1>Privacy Policy</h1><p class="article-meta">Effective: September 18, 2026</p><h2>Operator</h2><p>RushLabs operates FAA Part 107 (GLB-0002). Privacy questions: <a href="mailto:${supportEmail}">${supportEmail}</a>.</p><h2>Learning information</h2><p>The current app does not require a RushLabs account. Practice answers, saved items, progress, review history and preferences are stored locally on your device according to the current app implementation and listings.</p><h2>Purchases</h2><p>Google Play or the App Store handles payment information under its own policies. RushLabs does not receive card details through the app. Store product and transaction information may be used to determine access.</p><h2>Notifications and Lock Quiz</h2><p>Lock Quiz is optional. Question text remains hidden on the lock screen until you explicitly enable the feature. Device notification controls remain available to you.</p><h2>Support messages</h2><p>If you contact support, RushLabs receives what you voluntarily send. Do not send passwords, payment details, purchase tokens, receipts, aircraft registration details or private backups.</p><h2>This website</h2><p>This static website does not use analytics, advertising cookies, accounts or contact forms. External destinations apply their own privacy practices.</p></article>`;
const termsBody = `<article class="policy"><p class="eyebrow">Legal</p><h1>Terms of Use</h1><p class="article-meta">Effective: September 18, 2026</p><h2>Independent study aid</h2><p>The app is an independent exam-preparation product. It is not affiliated with or endorsed by the FAA and does not reproduce secured examination questions.</p><h2>No certification or operational authority</h2><p>Practice results do not grant a certificate, airspace authorization, waiver, registration or permission to fly. Current regulations, FAA guidance and issued authorizations control.</p><h2>Personal use and accuracy</h2><p>Use original learning material for personal study. Rules, guidance and testing policies can change. Current official sources control over summaries in the app or website.</p><h2>Store purchases</h2><p>Purchase only from the product name, duration, enabled features and full localized price shown in the Store-backed confirmation. Manage renewal, cancellation and refund requests through the purchasing Store account. Deleting the app does not cancel a subscription.</p><h2>Support</h2><p>Contact <a href="mailto:${supportEmail}">${supportEmail}</a>. These terms do not limit rights that cannot lawfully be excluded.</p></article>`;
const supportBody = `<section class="page-intro"><p class="eyebrow">App support</p><h1>Tell us what happened.</h1><p>Include the app name, device OS, app version and a short description. Screenshots help when they contain no private information.</p><a class="primary-button" href="mailto:${supportEmail}?subject=FAA%20Part%20107%20support">Email RushLabs support</a></section><section class="support-grid"><div><h2>Protect private information</h2><p>Do not send passwords, card information, purchase tokens, receipts, FAA account details or private backups.</p></div><div><h2>Purchases</h2><p>Use the purchasing Store account and Restore purchases where supported. Manage cancellation or refunds through the Store.</p></div><div><h2>Certification and operations</h2><p>Use FAA sources for certificates, regulations, airspace authorization, Remote ID and operating questions.</p></div></section>`;
const contactBody = `<section class="page-intro contact"><p class="eyebrow">Contact</p><h1>RushLabs</h1><p>For app support, privacy questions or factual corrections:</p><a class="contact-email" href="mailto:${supportEmail}">${supportEmail}</a><p class="source-note">Do not email passwords, payment details, FAA account information, purchase tokens or private learning data.</p></section>`;

await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });
await cp(join(root, "assets"), join(out, "assets"), { recursive: true });
await cp(join(root, ".nojekyll"), join(out, ".nojekyll"));
await cp(join(root, "assets", "app-icon.svg"), join(out, "favicon.svg"));
await cp(join(root, "styles.css"), join(out, "assets", "styles.css"));
await put("index.html", `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>FAA Part 107 Exam Prep</title><meta name="description" content="Independent FAA Part 107 practice and study guides."><meta http-equiv="refresh" content="0;url=./en/"><link rel="canonical" href="${origin}/en/"><script>location.replace('./en/')</script></head><body><main id="main"><p><a href="./en/">Continue to FAA Part 107 Exam Prep</a></p></main></body></html>`);
await put("en/index.html", layout({ title: "FAA Part 107 Exam Prep | Practice questions and flight guides", description: "Prepare for FAA Part 107 with original practice questions, explanations, practice tests and source-checked flight guides.", path: "/en/", body: homeBody, jsonLd: softwareSchema }));
await put("en/guides/index.html", layout({ title: "FAA Part 107 study guides", description: "Original Part 107 guides for certification, airspace, charts, weather, aircraft, risk and test-day preparation.", path: "/en/guides/", body: guidesBody }));
for (const article of articles) await put(`en/guides/${article.slug}/index.html`, articlePage(article));
await put("en/faq/index.html", layout({ title: "FAQ | FAA Part 107 Exam Prep", description: "Answers about Part 107 certification, recurrent training, app scope, privacy and Store availability.", path: "/en/faq/", body: faqBody, jsonLd: faqSchema }));
await put("en/privacy/index.html", layout({ title: "Privacy Policy | FAA Part 107 Exam Prep", description: "Privacy information for the FAA Part 107 Exam Prep app and website.", path: "/en/privacy/", body: privacyBody }));
await put("en/terms/index.html", layout({ title: "Terms of Use | FAA Part 107 Exam Prep", description: "Terms for FAA Part 107 Exam Prep, independent learning content and Store purchases.", path: "/en/terms/", body: termsBody }));
await put("en/support/index.html", layout({ title: "Support | FAA Part 107 Exam Prep", description: "Get help with FAA Part 107 Exam Prep, purchases, local progress and app issues.", path: "/en/support/", body: supportBody }));
await put("en/contact/index.html", layout({ title: "Contact RushLabs | FAA Part 107 Exam Prep", description: "Contact RushLabs about FAA Part 107 Exam Prep support, privacy or factual corrections.", path: "/en/contact/", body: contactBody }));
await put("404.html", layout({ title: "Page not found | FAA Part 107 Exam Prep", description: "The requested page could not be found.", path: "/404.html", body: `<section class="page-intro"><p class="eyebrow">404 · Off course</p><h1>This route is not in the flight plan.</h1><p>The study guides and app information are still available.</p><a class="primary-button" href="${base}/en/">Return home</a></section>` }));
const urls = ["/en/", "/en/guides/", ...articles.map((a) => `/en/guides/${a.slug}/`), "/en/faq/", "/en/privacy/", "/en/terms/", "/en/support/", "/en/contact/"];
await put("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map((path) => `  <url><loc>${origin}${path}</loc><lastmod>${checkedAt}</lastmod></url>`).join("\n")}\n</urlset>\n`);
await put("robots.txt", `User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
console.log(`Built ${urls.length} indexable pages in ${out}`);
